[api]
enabled = true
port = 54321

[functions.pages_system]
verify_jwt = false

[functions.stucheck_login]
verify_jwt = false

[functions.stucomplete_profile]
verify_jwt = false

[functions.stulogin]
verify_jwt = false

[functions.stuotp_request]
verify_jwt = false

[functions.stuready]
verify_jwt = false
