import { createClient } from "npm:@supabase/supabase-js@2.49.8";

const SUPABASE_URL              = Deno.env.get("SUPABASE_URL")               ?? "";
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")  ?? "";
const WAHA_URL                  = Deno.env.get("waha_url")                   ?? "";
const WAHA_API_KEY              = Deno.env.get("waha_api_key")               ?? "";

const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false }
  });

  const supabaseAuth = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

  Deno.serve(async (req: Request) => {
    if (req.method !== "POST") {
        return errorResponse("الطريقة غير مسموح بها", 405);
          }

            // ── 1. التحقق من الوقت (توقيت بغداد) ───────────────────────────
              // المسموح: من 12:00 صباحاً إلى 9:59 مساءً
                // الممنوع: من 10:00 مساءً (22:00) إلى 11:59 مساءً
                  const nowBaghdad     = new Date(new Date().toLocaleString("en-US", { timeZone: "Asia/Baghdad" }));
                    const currentHour    = nowBaghdad.getHours();
                      
                        if (currentHour >= 22) {
                            return errorResponse("لا يمكن الإستعداد في الوقت الحالي، أقصى وقت للإستعداد هو 10:00 مسائًا بتوقيت بغداد.", 403);
                              }

                                // ── 2. استخراج التوكن والتحقق من المستخدم ────────────────────────
                                  const authHeader = req.headers.get("Authorization") ?? "";
                                    const token      = authHeader.startsWith("Bearer ") ? authHeader.slice(7).trim() : "";

                                      if (!token) return errorResponse("يجب إرسال رمز المصادقة", 401);

                                        const { data: authData, error: authError } = await supabaseAuth.auth.getUser(token);
                                          if (authError || !authData?.user) return errorResponse("رمز المصادقة غير صالح", 401);

                                            const userId = authData.user.id;

                                              // ── 3. جلب بيانات المستخدم الأساسية و save_id ────────────────────
                                                const { data: user, error: userError } = await supabaseAdmin
                                                    .from("users")
                                                        .select("full_name, gender, user_phone_number, save_id")
                                                            .eq("user_id", userId)
                                                                .single();

                                                                  if (userError || !user) return errorResponse("المستخدم غير موجود", 404);

                                                                    const currentSaveId = user.save_id;
                                                                      if (!currentSaveId) return errorResponse("لا يوجد خطة حفظ نشطة لهذا المستخدم", 404);

                                                                        // ── 4. جلب حالة الخطة من users_saves ────────────────────────────
                                                                          const { data: savePlan, error: saveError } = await supabaseAdmin
                                                                              .from("users_saves")
                                                                                  .select("status")
                                                                                      .eq("id", currentSaveId)
                                                                                          .single();

                                                                                            if (saveError || !savePlan) return errorResponse("فشل الإستعداد يرجى التواصل مع إدارة المركز", 404);

                                                                                              const planStatus = savePlan.status;

                                                                                                // ── 5. معالجة الحالات المختلفة (ACTIVE, IN_EXAM1, IN_EXAM2) ────────
                                                                                                  let targetTable = "";
                                                                                                    let queryFilter: any = { save_id: currentSaveId };

                                                                                                      if (planStatus === "ACTIVE") {
                                                                                                          targetTable = "users_pages";
                                                                                                            } else if (planStatus === "IN_EXAM1") {
                                                                                                                targetTable = "users_pages_tests";
                                                                                                                    queryFilter.type = "EXAM1";
                                                                                                                      } else if (planStatus === "IN_EXAM2") {
                                                                                                                          targetTable = "users_pages_tests";
                                                                                                                              queryFilter.type = "EXAM2";
                                                                                                                                } else {
                                                                                                                                    return errorResponse("فشل الإستعداد يرجى التواصل مع إدارة المركز", 403);
                                                                                                                                      }

                                                                                                                                        // جلب آخر صف في الجدول المستهدف
                                                                                                                                          let query = supabaseAdmin.from(targetTable).select("*").eq("save_id", currentSaveId);
                                                                                                                                            if (targetTable === "users_pages_tests") {
                                                                                                                                                query = query.eq("type", queryFilter.type);
                                                                                                                                                  }
                                                                                                                                                    
                                                                                                                                                      const { data: lastRows, error: lastRowError } = await query
                                                                                                                                                          .order("id", { ascending: false })
                                                                                                                                                              .limit(1);

                                                                                                                                                                if (lastRowError || !lastRows || lastRows.length === 0) {
                                                                                                                                                                    return errorResponse("فشل الإستعداد يرجى التواصل مع إدارة المركز", 404);
                                                                                                                                                                      }

                                                                                                                                                                        const lastRow = lastRows[0];

                                                                                                                                                                          // ── 6. التحقق من حالة الصف الأخير ───────────────────────────────
                                                                                                                                                                            if (lastRow.status === "ready") {
                                                                                                                                                                                return errorResponse("فشل الإستعداد: تم الإستعداد من قبل.", 409);
                                                                                                                                                                                  }

                                                                                                                                                                                    if (lastRow.status !== "not_ready") {
                                                                                                                                                                                        return errorResponse("فشل الإستعداد يرجى التواصل مع إدارة المركز.", 403);
                                                                                                                                                                                          }

                                                                                                                                                                                            // ── 7. تحديث الحالة إلى ready ───────────────────────────────────
                                                                                                                                                                                              const { error: updateError } = await supabaseAdmin
                                                                                                                                                                                                  .from(targetTable)
                                                                                                                                                                                                      .update({
                                                                                                                                                                                                            status: "ready",
                                                                                                                                                                                                                  page_status: "ready",
                                                                                                                                                                                                                        ready_at: new Date().toISOString()
                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                .eq("id", lastRow.id);

                                                                                                                                                                                                                                  if (updateError) return errorResponse("حدث خطأ أثناء تحديث الحالة", 500);

                                                                                                                                                                                                                                    // ── 8. جلب بيانات المعلم وإرسال الرسالة ──────────────────────────
                                                                                                                                                                                                                                      const teacherId = lastRow.teacher_id;
                                                                                                                                                                                                                                        if (teacherId) {
                                                                                                                                                                                                                                            const { data: teacher } = await supabaseAdmin
                                                                                                                                                                                                                                                  .from("teachers")
                                                                                                                                                                                                                                                        .select("phone_number")
                                                                                                                                                                                                                                                              .eq("teacher_id", teacherId)
                                                                                                                                                                                                                                                                    .single();

                                                                                                                                                                                                                                                                        if (teacher?.phone_number) {
                                                                                                                                                                                                                                                                              const studentPhone = user.user_phone_number ?? "";
                                                                                                                                                                                                                                                                                    // تنسيق رقم الهاتف: حذف 964 ووضع 0
                                                                                                                                                                                                                                                                                          const formattedPhone = studentPhone.startsWith("964") 
                                                                                                                                                                                                                                                                                                  ? "0" + studentPhone.slice(3) 
                                                                                                                                                                                                                                                                                                          : studentPhone;

                                                                                                                                                                                                                                                                                                                const message = buildTeacherMessage(
                                                                                                                                                                                                                                                                                                                        user.full_name, 
                                                                                                                                                                                                                                                                                                                                user.gender === "female", 
                                                                                                                                                                                                                                                                                                                                        formattedPhone
                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                    await sendWahaMessage(teacher.phone_number, message);
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                            return successResponse();
                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                            // ┌─────────────────────────────────────────────────┐
                                                                                                                                                                                                                                                                                                                                                            //   بناء الرسالة للمعلم (تنسيق جميل مع إيموجي)
                                                                                                                                                                                                                                                                                                                                                            // └─────────────────────────────────────────────────┘
                                                                                                                                                                                                                                                                                                                                                            function buildTeacherMessage(fullName: string, isFemale: boolean, phone: string): string {
                                                                                                                                                                                                                                                                                                                                                              if (isFemale) {
                                                                                                                                                                                                                                                                                                                                                                  return [
                                                                                                                                                                                                                                                                                                                                                                        `🔔 *تنبيه إستعداد جديد*`,
                                                                                                                                                                                                                                                                                                                                                                              `────────────────`,
                                                                                                                                                                                                                                                                                                                                                                                    `🌸 لقد قامت الطالبة: *${fullName}*`,
                                                                                                                                                                                                                                                                                                                                                                                          `✅ بالإستعداد للتسميع الآن.`,
                                                                                                                                                                                                                                                                                                                                                                                                `📞 يرجى التواصل معها على الرقم:`,
                                                                                                                                                                                                                                                                                                                                                                                                      `👉 *${phone}*`,
                                                                                                                                                                                                                                                                                                                                                                                                            `────────────────`,
                                                                                                                                                                                                                                                                                                                                                                                                                  `وفقكم الله لما يحب ويرضى ✨`
                                                                                                                                                                                                                                                                                                                                                                                                                      ].join("\n");
                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                            return [
                                                                                                                                                                                                                                                                                                                                                                                                                                  `🔔 *تنبيه إستعداد جديد*`,
                                                                                                                                                                                                                                                                                                                                                                                                                                        `────────────────`,
                                                                                                                                                                                                                                                                                                                                                                                                                                              `👤 لقد قام الطالب: *${fullName}*`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    `✅ بالإستعداد للتسميع الآن.`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          `📞 يرجى التواصل معه على الرقم:`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                `👉 *${phone}*`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `────────────────`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `وفقكم الله لما يحب ويرضى ✨`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ].join("\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // ┌─────────────────────────────────────────────────┐
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //   إرسال رسالة عبر WAHA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // └─────────────────────────────────────────────────┘
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  async function sendWahaMessage(phone: string, text: string): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await fetch(WAHA_URL, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    headers: { "Content-Type": "application/json", "X-Api-Key": WAHA_API_KEY },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          body: JSON.stringify({ chatId: `${phone}@c.us`, text, session: "default" })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(`Error sending message to ${phone}:`, err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function errorResponse(message: string, status: number): Response {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            JSON.stringify({ error: true, errors: message }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { status, headers: { "Content-Type": "application/json" } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function successResponse(): Response {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        JSON.stringify({ error: false, message: "تم الإستعداد بنجاح، سيتم التواصل معك من قبل المعلم." }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { status: 200, headers: { "Content-Type": "application/json" } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
